MarketMakerReportsService:
  Db:
    DataConnectionString:
      settings-key: MarketMakerReportsService-DataConnectionString
      types:
        - AzureTableStorage
    
    LogsConnectionString:
      settings-key: MarketMakerReportsService-LogsConnectionString
      types:
        - AzureTableStorage
        
  Rabbit:
    AuditMessage:
      ConnectionString:
        settings-key: MarketMakerReportService-Rabbit-AuditMessage-ConnectionString
        types:
          - RabbitMq
      Exchange:
        settings-key: MarketMakerReportService-Rabbit-AuditMessage-Exchange
      Queue:
        settings-key: MarketMakerReportService-Rabbit-AuditMessage-Queue

    InventorySnapshot:
      ConnectionString:
        settings-key: MarketMakerReportService-Rabbit-InventorySnapshot-ConnectionString
        types:
        - RabbitMq
      Exchange:
        settings-key: MarketMakerReportService-Rabbit-InventorySnapshot-Exchange
      Queue:
        settings-key: MarketMakerReportService-Rabbit-InventorySnapshot-Queue

    LykkeTrade:
      ConnectionString:
        settings-key: MarketMakerReportService-Rabbit-LykkeTrade-ConnectionString
        types:
        - RabbitMq
      Exchange:
        settings-key: MarketMakerReportService-Rabbit-LykkeTrade-Exchange
      Queue:
        settings-key: MarketMakerReportService-Rabbit-LykkeTrade-Queue

    ExternalTrade:
      ConnectionString:
        settings-key: MarketMakerReportService-Rabbit-ExternalTrade-ConnectionString
        types:
        - RabbitMq
      Exchange:
        settings-key: MarketMakerReportService-Rabbit-ExternalTrade-Exchange
      Queue:
        settings-key: MarketMakerReportService-Rabbit-ExternalTrade-Queue

RateCalculatorServiceClient:
  ServiceUrl:
    settings-key: RateCalculatorServiceUrl

MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl
    
NettingEngineServiceClient:
  Instances:
    settings-key: NettingEngineServiceInstances
    types:
    - JsonArray
    
SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types:
        - AzureTableStorage
    
    QueueName:
      settings-key: SlackQueueName