MarketMakerReportsService:
  AssetsCacheExpirationPeriod: 01:00:00

  Db:
    DataConnectionString:
      settings-key: MarketMakerReportsService-DataConnectionString
      types:
      - AzureTableStorage

    LogsConnectionString:
      settings-key: MarketMakerReportsService-LogsConnectionString
      types:
      - AzureTableStorage

  Rabbit:
    AuditMessage:
      ConnectionString:
        settings-key: MarketMakerReportService-Rabbit-AuditMessage-ConnectionString
        types:
        - RabbitMq
      Exchange:
        settings-key: MarketMakerReportService-Rabbit-AuditMessage-Exchange
      Queue:
        settings-key: MarketMakerReportService-Rabbit-AuditMessage-Queue
      Enabled:
        settings-key: MarketMakerReportService-Rabbit-AuditMessage-Enabled

    InventorySnapshot:
      ConnectionString:
        settings-key: MarketMakerReportService-Rabbit-InventorySnapshot-ConnectionString
        types:
        - RabbitMq
      Exchange:
        settings-key: MarketMakerReportService-Rabbit-InventorySnapshot-Exchange
      Queue:
        settings-key: MarketMakerReportService-Rabbit-InventorySnapshot-Queue
      Enabled:
        settings-key: MarketMakerReportService-Rabbit-InventorySnapshot-Enabled

    LykkeTrade:
      ConnectionString:
        settings-key: MarketMakerReportService-Rabbit-LykkeTrade-ConnectionString
        types:
        - RabbitMq
      Exchange:
        settings-key: MarketMakerReportService-Rabbit-LykkeTrade-Exchange
      Queue:
        settings-key: MarketMakerReportService-Rabbit-LykkeTrade-Queue
      Enabled:
        settings-key: MarketMakerReportService-Rabbit-LykkeTrade-Enabled

    ExternalTrade:
      ConnectionString:
        settings-key: MarketMakerReportService-Rabbit-ExternalTrade-ConnectionString
        types:
        - RabbitMq
      Exchange:
        settings-key: MarketMakerReportService-Rabbit-ExternalTrade-Exchange
      Queue:
        settings-key: MarketMakerReportService-Rabbit-ExternalTrade-Queue
      Enabled:
        settings-key: MarketMakerReportService-Rabbit-ExternalTrade-Enabled

    HealthIssue:
      ConnectionString:
        settings-key: MarketMakerReportService-Rabbit-HealthIssue-ConnectionString
        types:
        - RabbitMq
      Exchange:
        settings-key: MarketMakerReportService-Rabbit-HealthIssue-Exchange
      Queue:
        settings-key: MarketMakerReportService-Rabbit-HealthIssue-Queue
      Enabled:
        settings-key: MarketMakerReportService-Rabbit-HealthIssue-Enabled

RateCalculatorServiceClient:
  ServiceUrl:
    settings-key: RateCalculatorServiceUrl

MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl

NettingEngineServiceClient:
  Instances:
    settings-key: NettingEngineServiceInstances
    types:
    - JsonArray

AssetsServiceClient:
  ServiceUrl:
    settings-key: AssetsServiceUrl

SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types:
      - AzureTableStorage

    QueueName:
      settings-key: SlackQueueName